# Generated by Django 5.1.15 on 2026-04-29 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('teachers', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='department',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.institution'),
        ),
        migrations.AddField(
            model_name='department',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='departments', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='session',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.institution'),
        ),
        migrations.AddField(
            model_name='stream',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='academics.classlevel'),
        ),
        migrations.AddField(
            model_name='stream',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.institution'),
        ),
        migrations.AddField(
            model_name='subject',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.institution'),
        ),
        migrations.AddConstraint(
            model_name='classlevel',
            constraint=models.UniqueConstraint(fields=('institution', 'name'), name='unique_classlevel_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('institution', 'name'), name='unique_department_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(fields=('institution', 'name'), name='unique_session_name_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='stream',
            constraint=models.UniqueConstraint(fields=('class_level', 'name'), name='unique_stream_per_class'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('institution', 'name'), name='unique_subject_name_per_institution'),
        ),
    ]
