# Generated by Django 5.1.15 on 2026-04-29 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('institution_key', models.CharField(db_index=True, max_length=6, unique=True)),
                ('motto', models.CharField(blank=True, max_length=255)),
                ('vision', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institution_logos/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='InstitutionBootstrapCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=150)),
                ('temporary_password', models.CharField(max_length=128)),
                ('delivered', models.BooleanField(default=False, help_text='Mark when these credentials have been handed over to the ICT Admin.')),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bootstrap_credentials', to='tenants.institution')),
            ],
            options={
                'verbose_name': 'Institution bootstrap credentials',
                'verbose_name_plural': 'Institution bootstrap credentials',
            },
        ),
    ]
